Repository fga-eps-mds/2019.2-Vsign, pull requests merged in 2019-10, with the labels that each got.

#90 Geração do Canvas do projeto
  docs/project/canvas.md
  docs/project/img/canvas.png
  mkdocs.yml
Labels: documentation, eps, good first issue

#104 Identidade visual
  docs/README.md
  docs/project/identidadeVisual.md
  docs/project/img/vsign_logo.png
  docs/project/roadmap.md
  docs/project/tap.md
  mkdocs.yml
Labels: documentation, eps, good first issue, pull request

#70 Criando template básico e estilos, deve ser melhorado
  frontend/src/components/SigningTips/SigningTips.css
  frontend/src/components/SigningTips/SigningTips.js
  frontend/src/routes.js
Labels: enhancement, mds, pull request

#106 Criação da EAP
  docs/project/eap.md
  docs/project/img/eap.png
  mkdocs.yml
Labels: documentation, eps, pull request, technical debt

#105 Versão 2 do roadmap dos papeis
  docs/project/img/Roadmap_Papeis_V2.png
  docs/project/roadmap.md
Labels: documentation, eps, invalid, pull request

#117 Documentar sprints
  docs/meetings/reuniao05_09_19.md
  docs/meetings/reuniao06_10_19.md
  docs/meetings/reuniao07_09_19.md
  docs/meetings/reuniao14_09_19.md
  docs/meetings/reuniao21_09_19.md
  docs/meetings/reuniao29_08_19.md
  docs/meetings/reuniao29_09_19.md
  docs/meetings/reuniao31_08_19.md
  docs/sprints/preSprint.md
  docs/sprints/sprint0.md
  docs/sprints/sprint1.md
  docs/sprints/sprint2.md
  docs/sprints/sprint3.md
  docs/sprints/sprint4.md
  docs/sprints/sprint5.md
  mkdocs.yml
Labels: documentation, eps, technical debt

#119 Criar Plano de Comunicação Interna
  docs/project/planoComunicacao.md
  mkdocs.yml
Labels: documentation, eps, technical debt

#115 Adding use cases diagram
  docs/project/img/useCasesDiagram.jpg
  docs/project/useCasesDiagram.md
  frontend/src/components/reviewUserVideo/index.js
  frontend/src/components/reviewUserVideo/styles.js
  mkdocs.yml
Labels: documentation, mds, technical debt

#128 Diagrama de classe
  docs/project/class-diagram.md
  docs/project/img/diagrama_de_classes_vsign.png
  mkdocs.yml
Labels: documentation, mds, technical debt
