Repository fga-eps-mds/2019.2-Vsign, pull requests merged in 2019-11, with the labels that each got.

#161 Autenticar Usuário
  backend/app/controllers/graphql_controller.rb
  backend/app/controllers/registrations_controller.rb
  backend/app/controllers/sessions_controller.rb
  backend/app/graphql/mutations/base_mutation.rb
  backend/app/graphql/mutations/login_user.rb
  backend/app/graphql/queries/base_query.rb
  backend/app/graphql/queries/current_user.rb
  backend/app/graphql/queries/get_contract.rb
  backend/app/graphql/types/contract_type.rb
  backend/app/graphql/types/mutation_type.rb
  backend/app/graphql/types/query_type.rb
  backend/app/graphql/types/user_type.rb
  backend/app/models/concerns/tokenizable.rb
  backend/app/models/user.rb
  backend/config/initializers/devise.rb
  backend/config/routes.rb
  backend/spec/controllers/registrations_controller_spec.rb
  backend/spec/controllers/session_controller_spec.rb
  frontend/src/App.js
  frontend/src/actions/contract.js
  frontend/src/actions/session.js
  frontend/src/actions/user.js
  frontend/src/components/ContractsPage/Contracts.js
  frontend/src/components/ContractsPage/contracts.json
  frontend/src/components/ContractsPage/index.js
  frontend/src/components/Instructions/Introduction.js
  frontend/src/components/LandingPage/Navbar.js
  frontend/src/components/LoginPage/index.js
  frontend/src/components/LoginPage/styles.js
  frontend/src/components/RecordPage/index.js
  frontend/src/components/ScriptPage/Script.js
  frontend/src/components/Shared/SigningSteps/index.js
  frontend/src/components/UploadImage/UploadImage.js
  frontend/src/constants/constract.js
  frontend/src/constants/session.js
  frontend/src/constants/user.js
  frontend/src/graphql/client.js
  frontend/src/graphql/mutations.js
  frontend/src/graphql/queries.js
  frontend/src/privateRouter.js
  frontend/src/reducers/contract.js
  frontend/src/reducers/index.js
  frontend/src/reducers/session.js
  frontend/src/reducers/user.js
  frontend/src/routes.js
  frontend/src/utils/checkToken.js
Labels: enhancement

#153 Seed para o banco de dados
  backend/Gemfile
  backend/Gemfile.lock
  backend/db/seeds.rb
Labels: enhancement, mds

#148 Face matching das fotos
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/jobs/face_match_job.rb
  backend/config/environments/development.rb
  backend/config/environments/production.rb
  backend/config/storage.yml
  backend/spec/jobs/face_match_job_spec.rb
Labels: enhancement, eps, mds, pull request

#164 Documento de assinatura necessário
  .gitignore
  backend/.gitignore
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/models/script.rb
  backend/db/migrate/20191112232725_add_document_to_script.rb
  backend/db/schema.rb
  backend/spec/models/script_spec.rb
Labels: enhancement, mds, pull request

#172 Added sprint 9 documentation
  docs/meetings/reuniao11_11_19.md
  docs/project/useCasesDiagram.md
  docs/sprints/sprint9.md
  mkdocs.yml
Labels: documentation, eps, pull request

#179 Article critical ananalysis
  .gitignore
  backend/.gitignore
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/graphql/mutations/attach_contract_files.rb
  backend/app/jobs/extract_audio_text_job.rb
  backend/app/jobs/face_match_job.rb
  backend/app/jobs/report_webhook_job.rb
  backend/app/models/script.rb
  backend/config/environments/development.rb
  backend/config/environments/production.rb
  backend/config/storage.yml
  backend/db/migrate/20191102183305_change_script_type_on_contract.rb
  backend/db/migrate/20191111200657_add_webhook_to_scripts.rb
  backend/db/migrate/20191112232725_add_document_to_script.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/spec/jobs/face_match_job_spec.rb
  backend/spec/jobs/report_webhook_job_spec.rb
  backend/spec/models/script_spec.rb
  docs/meetings/reuniao04_11_19.md
  docs/meetings/reuniao12_10_19.md
  docs/meetings/reuniao19_10_19.md
  docs/meetings/reuniao22_10_19.md
  docs/meetings/reuniao26_10_19.md
  docs/project/articleCriticalAnalysis.md
  docs/sprints/sprint6.md
  mkdocs.yml
Labels: documentation, eps, pull request

#178 Adição do protótipo de fidelidade
  docs/project/fidelity_prototyping.md
  mkdocs.yml
Labels: documentation, mds, pull request

#181 Enviar email quando novo contrato é criado
  backend/app/models/contract.rb
  backend/config/environments/development.rb
  backend/config/environments/production.rb
  backend/config/environments/staging.rb
  backend/config/routes.rb
Labels: enhancement

#137 Extrair informacoes do documento
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/jobs/id_check_job.rb
  backend/config/credentials.yml.enc
  backend/db/migrate/20191111145412_add_content_to_contract.rb
  backend/db/schema.rb
  backend/spec/jobs/id_check_job_spec.rb
Labels: enhancement, eps, mds, pull request, technical debt

#183 Testes de validação com Rspec
  backend/app/models/company.rb
  backend/app/models/contract.rb
  backend/app/models/script.rb
  backend/app/models/user.rb
  backend/spec/models/company_spec.rb
  backend/spec/models/contract_spec.rb
  backend/spec/models/script_spec.rb
  backend/spec/models/user_spec.rb
  docs/project/postmortem.md
  mkdocs.yml
Labels: test

#187 Postmortem
  .mailmap
  backend/Gemfile.lock
  docs/meetings/reuniao11_11_19.md
  docs/project/articleCriticalAnalysis.md
  docs/project/class-diagram.md
  docs/project/identidadeVisual.md
  docs/project/img/diagrama_de_classes_vsign.png
  docs/project/postmortem.md
  docs/project/useCasesDiagram.md
  docs/sprints/sprint9.md
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/images/header2.png
  frontend/src/components/Script.js
  frontend/src/components/ScriptPage.css
  frontend/src/components/ScriptPage/teste.js
  frontend/src/index.css
  mkdocs.yml
Labels: documentation, eps, mds, pull request

#165 Matching das Informações do Documento com as do Contrato
  .circleci/config.yml
  backend/Gemfile.lock
  backend/app/jobs/id_check_job.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/spec/rails_helper.rb
  backend/spec/spec_helper.rb
Labels: enhancement, eps, mds, pull request

#162 Validar Documento do Usuário
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/jobs/id_confirm_job.rb
  backend/spec/jobs/id_confirm_job_spec.rb
  frontend/src/App.js
Labels: enhancement, eps, mds, pull request

#191 Documentation refactoring
  docs/project/architectureDocument.md
  docs/project/identidadeVisual.md
  docs/project/img/Use_cases_Diagram.jpg
  docs/project/img/useCasesDiagram.jpg
  docs/project/planoComunicacao.md
  docs/project/useCasesDiagram.md
  docs/project/vision-document.md
Labels: documentation, eps, mds, pull request
