Repository fga-eps-mds/2019.2-Vsign, pull requests merged in 2019-09, with the labels that each got.

#28 Architecture document
  docs/architectureDocument/doc.md
  mkdocs.yml
Labels: documentation, mds

#60 US05 - Versionar API Rest
  backend/config/routes.rb
Labels: enhancement

#49 Tap
  docs/managementProject/gcs.md
  docs/project/architectureDocument.md
  docs/project/img/cronograma.png
  docs/project/tap.md
  docs/project/vision-document.md
  mkdocs.yml
Labels: documentation, eps, good first issue, pull request, technical debt

#88 Criação dos Roadmaps
  docs/project/img/Roadmap_Codigo.png
  docs/project/img/Roadmap_Papeis.png
  docs/project/img/Roadmap_Projeto.png
  docs/project/roadmap.md
  mkdocs.yml
Labels: documentation, eps, technical debt
